[package]
name = "hyprduel_server"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
futures-util = "0.3"
log = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "*"
